[settings]
experimental = true

[env]
HK_LIBGIT2 = 0
TERM = "xterm-256color"
EDITOR = "nano"
KUBE_EDITOR = "nano"
COMPOSE_BAKE = true
OP_RUN_NO_MASKING = true
HK_MISE = 1
UV_PREVIEW = 1
MISE_NPM_BUN = 1

[tasks.sysupg]
description = "Full system upgrade"
run = '''
    topgrade -y --no-retry --disable vscode jetbrains_toolbox jetbrains_pycharm jetbrains_clion \
        jetbrains_goland jetbrains_rustrover oh-my-bash
'''

[tools]
