# "deployment tools" (server)

rust = "stable"
go = "latest"
zig = "latest"
zls = "latest"
lua = "latest"

node = "latest"
npm = "latest"
pnpm = "latest"
bun = "latest"

semver = "latest"
dust = "latest"
bottom = "latest"
gh = "latest"
bat = "latest"
eza = "latest"
jless = "latest"
sd = "latest"
fd = "latest"
rg = "latest"
jq = "latest"
yq = "latest"
jqp = "latest"
yazi = "latest"
zoxide = "latest"
starship = "latest"

chezmoi = "latest"
fnox = "latest"
powershell = "latest"
zellij = "latest"
television = "latest"

cargo = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:topgrade" = "latest"
"cargo:dysk" = "latest"
"cargo:nu" = "latest"
