# linux tools (server)

semver = "latest"
dust = "latest"
bottom = "latest"
gh = "latest"
bat = "latest"
eza = "latest"
jless = "latest"
fd = "latest"
rg = "latest"
jq = "latest"
yq = "latest"
jqp = "latest"
yazi = "latest"
zoxide = "latest"
starship = "latest"

chezmoi = "latest"
just = "latest"
fnox = "latest"
powershell = "latest"
zellij = "latest"
television = "latest"
rclone = "latest"
aws-cli = "latest"
ruff = "latest"
shellcheck = "latest"
